problems/baekjoon/01_입출력과 사칙연산/10869_사칙연산/saehan.js, problems/baekjoon/01_입출력과 사칙연산/2557_Hello World/saehan.js, problems/baekjoon/02_조건문/9498_시험 성적/saehan.js
1hours
-  백준 초기 설정하는데 어려움이 있었다.
-  코딩테스트를 제대로 진행해보는 것이 처음이라 pull request 작성이며, git branch로 push 등 어색하지만 조원들의 도움으로 하니씩 해결해서 좋았다.
=> [1주차] - 윤새한 과제제출

problems/baekjoon/01_입출력과 사칙연산/10869_사칙연산/bohwa.js, problems/baekjoon/01_입출력과 사칙연산/2557_Hello World/bohwa.js, problems/baekjoon/02_조건문/9498_시험 성적/bohwa.js
- 30분(?) 근데 깃허브 올리는데는 6-7시간 헤맸다....ㅠ
- 백준을 vs코드에서 다룰때 아직 이해 안가는 부분이 있다.
- 깃허브 잘 다룰줄 몰라서 사실 그동안 방치하고 있었는데, 막상 과제 제출하려니 안돼서 혼자 6시간은 헤맸다. 근데 새벽에 주희님이 구세주처럼 1:1 과외해주셔서 깃허브에 올릴 수 있게되었다. 깃허브 이해못했는데 과외받은 덕분에 퍼즐이 맞춰지기 시작한다. 
- 사람의 중요성을 다시금 느꼈다. 나도 언젠간 누군가에게 꼭 도움주고 싶다..!
- 스터디 하길 잘했다 생각했다.
- 강의 맨날 들어도 실습 해봐야한단걸 느꼈다.  
- 아직 배울게 많은 코린이라서 피드백 부탁드립니당
- 10869번 사칙연산 문제에서
let num1 = 7
let num2 = 3
이렇게 7과 3이라고 값을 정해도 괜찮은지도(?)
궁금합니당
=> [1주차] 정보화 과제 제출

problems/baekjoon/01_입출력과 사칙연산/10869_사칙연산/README.md, problems/baekjoon/01_입출력과 사칙연산/10869_사칙연산/hyunwoo.js, problems/baekjoon/01_입출력과 사칙연산/2557_Hello World/README.md, problems/baekjoon/01_입출력과 사칙연산/2557_Hello World/hyunwoo.js, problems/baekjoon/02_조건문/9498_시험 성적/README.md, problems/baekjoon/02_조건문/9498_시험 성적/hyunwoo.js
1시간
- input받는게 헷갈렸고, 타입변환하는데에도 어려움을 겪었습니다.
- 자바스크립트 나눗셈은 소수점 버림이 필요하다.
=> [1주차] 이현우 과제 제출

problems/baekjoon/01_입출력과 사칙연산/10869_사칙연산/jaeseok.py, problems/baekjoon/01_입출력과 사칙연산/2557_Hello World/jaesoeok.py, problems/baekjoon/02_조건문/9498_시험 성적/jaeseok.py
5min
- 이번 주는 없습니다.
- 최근 프로그래머스만 해서 입출력이 기억이 안 났는데, 백준 문제 풀이를 통해 map함수를 다시 복습할 수 있었습니다.
1. 파이썬으로 작업하였는데 이해가 되었는지 궁금합니다.
2. 코드의 길이는 어떤가요??
=> [1주차] 박재석 과제 제출

problems/baekjoon/01_입출력과 사칙연산/10869_사칙연산/moonju.js, problems/baekjoon/01_입출력과 사칙연산/2557_Hello World/moonju.js, problems/baekjoon/02_조건문/9498_시험 성적/moonju.js
- 문제풀이: 30분 정도
- 초기 환경세팅이 어려웠다.
- 백준으로 처음 코테를 준비하는 것이라 초기세팅하는 법이랑 문제 푸는 법을 배웠습니다.
=> [1주차] 김문주 과제 제출

problems/baekjoon/01_입출력과 사칙연산/10869_사칙연산/seonguk.js, problems/baekjoon/01_입출력과 사칙연산/2557_Hello World/seonguk.js, problems/baekjoon/02_조건문/9498_시험 성적/seonguk.js
2557 1분
10869 5분
9498 5분
- 
if, else 가 아닌 다른 풀이법이 많다. 더욱 간단하고 효율적인 면이 보여 공부를 해야할 것 같다.
많은 코멘트 바람 ~~
=> [1주차] 홍성욱 과제 제출

problems/baekjoon/01_입출력과 사칙연산/10869_사칙연산/seohyeon.js, problems/baekjoon/01_입출력과 사칙연산/2557_Hello World/seohyeon.js, problems/baekjoon/02_조건문/9498_시험 성적/seohyeon.js
- 문제풀이 : 10분 
- 세팅하고 제출까지 : 2시간
- 백준 문제를 이렇게 vs code로 가져와서 푼적은 첨이라,
특히 javascript로 푼적은 첨이라 초기 환경세팅이 쉽지 않았지만 부딪히고 나니 잘 배운거 같습니다 :)
- 백준이 정답제출할때 javascript 언어가 아닌, node.js방식으로 제출하기 때문에, fs모듈방식 등을 이용해 제출해야한다는 점!!
- 오늘 코드적인 부분은 간단했습니다.
=> [1주차] 김서현 과제 제출

problems/baekjoon/02_조건문/2884_알람 시계/format/hyunwoo.js, problems/baekjoon/03_반복문/25304_영수증/hyunwoo.js, problems/baekjoon/04_1차원 배열/5597_과제안내신분/README.md, problems/baekjoon/04_1차원 배열/5597_과제안내신분/hyunwoo.js
30분
- x
- 어떤 자료형을 써야 적게 메모리를 잡을 수 있을지 (생각만 해봤다..)
편하게 지적 부탁드려요!
=> [2주차] 이현우 과제 제출

problems/baekjoon/02_조건문/2884_알람 시계/format/README.md, problems/baekjoon/02_조건문/2884_알람 시계/format/seohyeon.js, problems/baekjoon/03_반복문/25304_영수증/seohyeon.js, problems/baekjoon/04_1차원 배열/5597_과제안내신분/seohyeon.js
15min
30min
30min
- 영수증 문제에서 입력값을 받아오는 것부터 쉽지 않았다. 
splice써서 input을 제거해버렸고 다시 input을 받아오는개념으로
개행 -> 공백 띄우기로 된 입력값을 받아와 처리했다.
- 1차원 배열 문제인 과제안내신분 문제는 for문을 두번썼는데 괜찮은지 모르겠다(?)
그리고 마지막 답을 낼때 개행을 나타내느라 시간을 많이썼다. 
결론은 .join("\n")을 쓰니 배열->문자열로 개행으로 표현가능했다.
- .split() : 문자열을 일정한 구분자로 잘라서 배열로 저장.
- array.splice(0,2) : 앞은 시작할 인덱스, 뒤는 그만큼의 갯수. 즉, 0번인덱스의 배열을 2개 제거하는 것이다.
- .join( ) : 배열의 모든 값들을 연결한 문자열을 리턴 
5597번이 특히 너무 제 생각대로만 코드를 짜서,,,
체크해주시고 다양한 조언 및 코멘트 부탁합니다 ㅎㅎ~ : )
=> [2주차] 김서현 과제 제출

problems/baekjoon/02_조건문/2884_알람 시계/format/jaeseok.py, problems/baekjoon/03_반복문/25304_영수증/jaeseok.py, problems/baekjoon/04_1차원 배열/5597_과제안내신분/jaeseok.py
30min
- 2884번 알람 시계 문제를 풀면서 조건을 어떻게 나눌지에 대한 고민이 있었다.
- for 문을 통해 입력값을 받을 수 있다는 것을 remind 시켰다.
1. 변수명이 이해가 되었나요???
2. 코드 refactoring 부분이 있었나요??
=> [2주차] 박재석 과제 제출

problems/baekjoon/02_조건문/2884_알람 시계/format/seonguk.js, problems/baekjoon/03_반복문/25304_영수증/seonguk.js, problems/baekjoon/04_1차원 배열/5597_과제안내신분/seonguk.js
2884 5분
25304 5분
5597 10분
X
5597 배열의 차이를 계산할 때 어떤 함수를 쓰면 효율적일지 고민해 봄
많은 비판과 사랑 바랍니다 :)
=> [2주차] 홍성욱 과제 제출

problems/baekjoon/05_함수/4673_셀프 넘버/jaeseok.py, problems/baekjoon/06_문자열/11720_숫자의 합/jaeseok.py, problems/baekjoon/07_기본수학1/1712_손익분기점/jaeseok.py
4673 - 15 min
11720 - 5 min
1712 - 3 min
- 4673번에서 처음에 내장형 함수를 이용하려다가 함수를 만들면 되다는 것을 너무 늦게 깨달아 버렸다..
- 너무 내장된 함수를 이용하기보다는... 내가 직접 함수를 만들어서 사용하자!!!
1. 파이썬 관련해서 언제든 궁금한 부분이 있으면 물어봐 주세요!!!
2. 4673번 셀프 넘버 문제에서 만든 함수가 이해가 되나요??
=> [3주차] 박재석 과제 제출

problems/baekjoon/05_함수/4673_셀프 넘버/hayeon.js, problems/baekjoon/06_문자열/11720_숫자의 합/hayeon.js, problems/baekjoon/07_기본수학1/1712_손익분기점/hayeon.js
셀프넘버때문에 좀 생각할 시간이 길어졌습니다! 시간은..정확히 모르겠어유
- 셀프넘버를 풀때 문제는 이해가 가는데 입력방식이 없는 문제는 처음이라..어떻게 풀어야할지 고민이 많았습니다😭
- 그리구 각 자릿수를 구해서 누적합해주는 부분이 쪼곰 생소했던것 같아요.
- 예시가 10000개가 넘는 것도 처음 봐서 조금 당황했습니당.
- 각 자릿수를 구하는 방법을 터득했다!!
- 손익분기점 풀 때 단순히 x를 구하는것이 아닌 풀어서? 보는 방법을 터득했다.
- 많이 부족할수도 있는데 다들 다양한 리뷰 부탁드려요!!🙇‍♀️
=> [3주차] 김하연 과제 제출

problems/baekjoon/05_함수/4673_셀프 넘버/seonguk.js, problems/baekjoon/06_문자열/11720_숫자의 합/seonguk.js, problems/baekjoon/07_기본수학1/1712_손익분기점/seonguk.js
1712 2시간
4673 3시간
11720 10분
- 셀프넘버의 경우 셀프넘버의 정의 자체를 이해하지 못하여서 시간이 지체되었다.
- 손익분기점 같은 경우는 다른 공식을 만들었다가, 이보다 더 효율적인 공식을 찾게되어 시간이 꽤 걸렸던 것 같다.
갈 길이 멀다,,
매운 지적 부탁드립니다 :)
=> [3주차] 홍성욱 과제 제출

problems/baekjoon/05_함수/4673_셀프 넘버/hyunwoo.js, problems/baekjoon/06_문자열/11720_숫자의 합/hyunwoo.js, problems/baekjoon/07_기본수학1/1712_손익분기점/hyunwoo.js
3시간
- 손익분기점 수식을 세우는데 어려웠는데 질문을 통해 해결할 수 있었다. 무작정 코딩하기보다는 사전에 손코딩을 하는 것을 추천받았다. 👍
- 수학문제이니까 수식을 구해야 문제를 편하게 풀 수 있다..
- 수식을 잘 구하면 완전탐색할 필요가 없는 문제를 만났다.
- 항상 주어지는 범위를 잘 살피고, 시간복잡도를 생각해보고 풀자
편하게 지적해주세요!
=> [3주차] 이현우 과제 제출

problems/baekjoon/06_문자열/11720_숫자의 합/seohyeon.js, problems/baekjoon/07_기본수학1/1712_손익분기점/seohyeon.js
20분
20분
- 4623 셀프넘버 못품
- 셀프넘버 문제는 문제자체가 일단 이해가 안되서 검색해서 다른분꺼 읽어봐도 이해가 안되서 풀이를 작성하지 못했습니다..ㅠ
- 팀원분들 코드를 세세히 읽어보고 문제를 이해해보도록 노력하겠습니다.
- slice는 string을 쪼갠다는 점. for문쓸때 무한루프 돌리면 안되구나..하는점
1712 손익분기점 문제에서 for문 범위를 정해주지 않아서 무한루프를 돌고 해당하면 break해서 빠져나오는 식으로 코드를 짰는데, 백준에 답을 입력하니 틀렸다고 나왔습니다.. 
무한루프는 정말 쓰면 안되는건지, 만약 제 코드를 그대로 유지한다면 for문에 범위를 무한루프대신 뭐라고 쓰는게 좋을지
궁금합니다 ㅠ.ㅠ
=> [3주차] 김서현 과제 제출

problems/baekjoon/05_함수/4673_셀프 넘버/bohwa.js, problems/baekjoon/06_문자열/11720_숫자의 합/bohwa.js, problems/baekjoon/07_기본수학1/1712_손익분기점/bohwa.js
6시간 그이상 넘은듯........
- 셀프넘버 진짜어렵네
- 혼자 1시간정도씩 고민해보다가 모르면 답봤다. 
- 3문제 전부 다 답참고했다...^^;
- fill에 대해 배움
- 비판 환영합니다 감사합니다
=> [3주차] 정보화 과제 제출

problems/baekjoon/08_기본수학2/11653_소인수분해/juhee.js, problems/baekjoon/09_2차원 배열/2566_최댓값/juhee.js, problems/programmers/lv0/최빈값 구하기/juhee.js
1.5 ~ 2 hour
- 최빈값 구하기 문제가 쫌.. 어려웠숨당... 키 밸류 값으로 최빈값을 계산해야겠다! 라는 아이디어는 얻었는데..
그 이후로 풀기가 조금 어려웠어서 결국 구글링했습니다! 구글링 하고 나서는 이해했어요! map 체화하는데 시간이 조금 필요할 것 같습니당.
- map.get() 메소드로 입력받은 parameter와 key 값이 일치하는 value 값을 출력해낼 수 있다.
- map.set() 메소드로 parameter로 입력받은 key와 value 값을 저장한다.
2차원배열 문제를 이중 for문을 사용하지 않고 풀어보고 싶은데 어렵네요ㅠㅠ
코드리뷰 환영이요!!
=> [4주차] 황주희 과제 제출 

problems/baekjoon/08_기본수학2/11653_소인수분해/jaeseok.py, problems/baekjoon/09_2차원 배열/2566_최댓값/README.md, problems/baekjoon/09_2차원 배열/2566_최댓값/jaeseok.js, problems/baekjoon/09_2차원 배열/2566_최댓값/jaeseok.py, problems/programmers/lv0/최빈값 구하기/jaeseok.py
BOJ 11653 - 15min
BOJ 2566 - 1hr
PRG 최빈값 구하기 - 30min
- JS를 오랜만에 풀어서 입력값 받는 부분에서 시간이 조금 소요가 되었다.
- JS 입력받는 코드를 배울 수 있었다.
=> [4주차] 박재석 과제 제출

problems/baekjoon/08_기본수학2/11653_소인수분해/bohwa.js, problems/baekjoon/09_2차원 배열/2566_최댓값/bohwa.js, problems/programmers/lv0/최빈값 구하기/bohwa.js
7시간정도
- 소인수분해빼고 나머지 2문제 진이인짜 어려워서 정답지봤습니다..
- Map에 대해 배웠다.
- 지적 환영. 감사합니다.
=> [4주차] 정보화 과제 제출

problems/baekjoon/08_기본수학2/11653_소인수분해/hyunwoo.js, problems/baekjoon/09_2차원 배열/2566_최댓값/hyunwoo.js, problems/programmers/lv0/최빈값 구하기/hyunwoo.js
✨ 푼 문제
BOJ 11653 [x]
BOJ 2566 [x]
PRG 최빈값 구하기 [x]
⏰ 소요시간
BOJ 11653 - 15min
BOJ 2566 - 15hr
PRG 최빈값 구하기 - 120min
🥲 어려웠던 점
최빈값 풀다 인내심에 한계가 올뻔했다.
🤩 배운 점
자바스크립트로 2차원 배열 쓰는법을 배웠다.
🙏🏻 코드리뷰 요청사항
편하게 피드백 부탁드리겠습니다!
=> [4주차] 이현우 과제 제출

problems/baekjoon/08_기본수학2/11653_소인수분해/seohyeon.js, problems/baekjoon/09_2차원 배열/2566_최댓값/seohyeon.js, problems/programmers/lv0/최빈값 구하기/seohyeon.js
30분
1시간이상 후 못품
- 2566, 최빈값 구하기 문제들을 못풀어서 검색을 하여 참고하였습니다..ㅠ
- flat()으로 배열 합치기,
- indexOf 활용, 
2566번 너무 이해가 안되서 모르는 부분 주석으로 표시했습니다 ㅠ
몇 행 몇 열인지 구하기 부분이 정말 모르겠습니다 한번 체크 부탁드립니다!!
=> [4주차] 김서현 과제 제출

problems/programmers/lv0/최빈값 구하기/moonju.js
- BOJ 11653
- BOJ 2566
하나라도 제대로 풀기위해 최빈값 구하기에 집중했다.
- 얼른 함수에 익숙해 져서 메소드나 배열등을 자유롭게 사용하고 싶다.
- 최대한 for문이나 while문을 이용해 코드에 익숙해지고 있습니다.
- 못 푼 문제가 많아서... 최빈값 구하기라도 코드리뷰 부탁드립니다.
=> [4주차] 김문주 과제 제출

problems/baekjoon/05_함수/1065_한수/hyunwoo.js, problems/baekjoon/10_정렬/2587_대표값2/hyunwoo.js, problems/programmers/lv0/진료순서/hyunwoo.js
1065 한수 30분
2587 대표값2 10분
진료순서 10분
- 
- 
많은 피드백 부탁드려여!
=> [5주차] 이현우 과제 제출

problems/baekjoon/05_함수/1065_한수/jaeseok.py, problems/baekjoon/10_정렬/2587_대표값2/jaeseok.py, problems/programmers/lv0/진료순서/jaeseok.py
- BOJ 1065 : 10min
- BOJ 2587 : 2min
- PGM 진료순서 : 3min
- BOJ 1065 : 한수의 의미를 파악하는데 시간이 조금 걸렸다.
- 입력값을 각각의 자릿수를 분리시키는 방법을 배웠다.
- 파이썬 관련하여 궁금한 부분은 언제든 문의주세요!!!
=> [5주차] 박재석 과제 제

problems/baekjoon/05_함수/1065_한수/bohwa.js, problems/baekjoon/10_정렬/2587_대표값2/bohwa.js, problems/programmers/lv0/진료순서/bohwa.js
5시간정도??
- 나머지 2개는 풀만했는데, 한수가 꽤나 어려웠다.
- 예제출력에 힌트가 있다는걸 알았다. 지금까지는 예제출력은 대충보고 넘겼던것같은데..
- 리뷰 감사드립니다.!
=> [5주차] 정보화 과제 제출

problems/baekjoon/05_함수/1065_한수/moonju.js, problems/programmers/lv0/진료순서/moonju.js
- 한 문제당 1시간 정도 걸림.
- 한수 문제를 이해하는데 오래 걸렸다.
- 문제를 얼마나 가독성 있게 풀지 고민해 봐야겠다. (메서드, 최대한 짧게...)
-  sort() 메서드를 사용함. 
- 아직 다양한 메서드나 함수를 이용해서 풀진 못하지만 다양한 의견 부탁드립니다.🙇‍♀️
=> [5주차] 김문주 과제 제출

problems/baekjoon/05_함수/1065_한수/seonguk.js, problems/baekjoon/10_정렬/2587_대표값2/seonguk.js, problems/programmers/lv0/진료순서/seonguk.js
1065 한수 1시간
2587 대표값2 5분
진료순서 10분
-
한수의 문제에서 계산하지 않을 경우는 과감하게 생략(하지 않을 경우는 스포일러 같아 노코멘트)하여 계산 시간을 확실하게 줄일 수 있었다. 좀더 효율적이고 직관적인 코드를 짜볼 수 있었다고 생각한다.
많관부 ~~
=> [5주차] 홍성욱 과제 제출

problems/baekjoon/05_함수/1065_한수/juhee.js, problems/baekjoon/10_정렬/2587_대표값2/juhee.js, problems/baekjoon/DFSBFS/1260_DFS와 BFS/juhee.js, problems/programmers/lv0/진료순서/juhee.js
2hours
- git이 꼬여서.. PR이 안올라갔었다.. 정확한 원인 파악은 하지 못했지만 해결은 되었다.
추측하는 것으로는 개인 브랜치에서 작업하다가 중간에 main 브랜치에서 수정사항을 push한 뒤, 
다시 개인 브랜치에서 작업하고 push하는 과정에서
"Merge remote-tracking branch 'origin/main' into Juhee"로 적힌 커밋 때문인 것 같다.
main 브랜치에서 파일을 초기화하고, 개인 브랜치에서 다시 pull 받아서 작업을 해도 main에 바로 반영되는 문제를 가지고 있는데..
다음에 비슷한 상황이 발생했을 때 어떻게 해결해야 할지 알고 싶다!
-   숫자 혹은 문자로 이루어진 배열.slice()해주면 깊은 복사가 된다.
피드백 환영합니다~
=> [5주차] 황주희 과제 제출

problems/baekjoon/05_함수/1065_한수/seohyeon.js, problems/baekjoon/10_정렬/2587_대표값2/seohyeon.js, problems/programmers/lv0/진료순서/seohyeon.js
20분
1시간 후 풀이참고해서 품
1시간 후 풀이참고해서 품
- map, slice,splice이용이 능숙하지 못했음
- 한수문제 자체를 이해하는데 시간이 걸렸음.
- 각 자리수를 나타낼때 String으로 형변환하는 생각.
- 코드 가독성, 간결성 피드백 부탁합니다~
=> [5주차] 김서현 과제 제출

problems/baekjoon/1978_소수 찾기/jaeseok.py, problems/programmers/lv0/팩토리얼/jaeseok.py, problems/programmers/lv0/피자 나눠 먹기 2/jaeseok.py
- PG 팩토리얼 : 5min
- PG 피자 나눠 먹기 2 : 2min
- BOJ 1978_소수 찾기 : 5min
- 이번 주는 딱히 없었습니다.
- 소수를 판단하는 함수를 다시 생각해 볼 수 있었다.
궁금한 부분은 무엇이든 리뷰해주세요!!!
=> [6주차] 박재석 과제 제출

problems/baekjoon/1978_소수 찾기/README.md, problems/baekjoon/1978_소수 찾기/hyunwoo.js, problems/programmers/lv0/팩토리얼/hyunwoo.js, problems/programmers/lv0/피자 나눠 먹기 2/hyunwoo.js
팩토리얼 : 10min
피자 나눠 먹기 2 : 10min
BOJ 1978_소수 찾기 : 10min
- 
- 
날카로운 피드백 언제나 환영입니다!
=> [6주차] 이현우 과제 제출

problems/baekjoon/1978_소수 찾기/saehan.js, problems/programmers/lv0/팩토리얼/saehan.js, problems/programmers/lv0/피자 나눠 먹기 2/saehan.js
프로그래머스 2 문제 1시간 씩
백준 소수 찾기 문제 2시간
-  수식에 대한 이해가 있어야 풀 수 있는 문제가 있었다.
-  소수 찾기의 경우 배열로 뽑아내는 과정에서 헤맸다.
- NaN로 찍히는 배열을 map으로 형변환을 통해 새로운 배열을 뽑아내고 filter를 이용해 함수로 정의한 값을 도출해낼 수 있었다.
=> [6주차] 윤새한 과제 제출

problems/baekjoon/1978_소수 찾기/seonguk.js, problems/programmers/lv0/팩토리얼/seonguk.js, problems/programmers/lv0/피자 나눠 먹기 2/seonguk.js
팩토리얼 5분
피자 나눠 먹기 5분
소수 찾기 1시간
- 
Array().fill() 의 활용
많은 리뷰 부탁드립니다 :)
=> [6주차] 홍성욱 과제 제출

problems/programmers/lv0/팩토리얼/moonju.js, problems/programmers/lv0/피자 나눠 먹기 2/moonju.js
- 각각 한시간씩 걸렸습니다
- 소수 찾기 문제는 천천히 뜯어봐야겠다. 😭 
- 
- 리뷰 부탁드립니다!
=> [6주차] 김문주 과제 제출

problems/baekjoon/1978_소수 찾기/bohwa.js, problems/programmers/lv0/팩토리얼/bohwa.js, problems/programmers/lv0/피자 나눠 먹기 2/bohwa.js
6시간정도 걸렸따.
- 소수찾기가 특히 어려웠다.
- 필터에 대해 배웠다.
감사합니다 ^^
=> [6주차] 정보화 과제 제출

problems/baekjoon/1978_소수 찾기/juhee.js, problems/programmers/lv0/팩토리얼/juhee.js, problems/programmers/lv0/피자 나눠 먹기 2/juhee.js
잘.. 몰라요... 오래대가지구...
- 딱히 없는데, 그냥 생각 나는대로 코드를 쳐서 이쁜 코드는 아니에요.. ㅎㅎㅎ
- 
효율적인 코드 필요...
=> [6주차] 황주희 과제 제출
